sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"
script:
  - make clean
  - make
#  - make test
